export const events = [
    {
      id: 1,
      name: "Воркшоп «Керамическая кружка своими руками» от Оразбай Күнерке",
      category: "Образование и мастер-классы",
      date: "14 Декабря",
      location: "Творческое пространство Mount Orta, ул. Смагулова, 9/1",
      time: "19:00",
      price: 16000,
      description: "Приглашаем вас создать свою уникальную кружку из глины...",
      url: "https://sxodim.com/uploads/posts/2024/12/09/optimized/30db7b7edffc79cec44fbb6946dd005f_545x305-q-85.jpg"
    },
    {
      id: 2,
      name: "Разговорный клуб английского языка в Mount Orta: Рождество и Новый год",
      category: "Образование и мастер-классы",
      date: "14 Декабря",
      location: "Творческое пространство Mount Orta, ул. Смагулова, 9/1",
      time: "19:00",
      price: 3000,
      description: "Присоединяйтесь к разговорному клубу...",
      url: "https://sxodim.com/uploads/posts/2024/12/09/optimized/3723ff067d463987de33e7f7446864fe_1400x790-q-85.jpg"
    },
    {
      id: 3,
      name: "Лекция «Игры разума и сна: искусство сюрреалистов»",
      category: "Образование и мастер-классы",
      date: "12 Декабря",
      location: "Творческое пространство Mount Orta, ул. Смагулова, 9/1",
      time: "19:00",
      price:0,
      description: "Обсудим искусство сюрреализма...",
      url: "https://sxodim.com/uploads/posts/2024/12/09/optimized/73be50bb47fa76b31766ac2f5ec144e7_1522x570-q-85.jpg"
    },
    {
      id: 4,
      name: "Разговорный клуб на английском языке для начинающих",
      category: "Образование и мастер-классы",
      date: "5 Декабря",
      location: "Mount Orta, ул. Смагулова, 9/1",
      time: "19:00",
      price: 0,
      description: "Клуб для изучающих английский...",
      url: "https://www.poliglotiki.kz/images/kz/pages/anglijskij-yazyk-razgovornyj-klub.jpg"
    },
    {
      id: 5,
      name: "Концерт: Джазовый вечер с Джулией Симонс",
      category: "Музыка и концерты",
      date: "20 Декабря",
      location: "Jazz Hall Aktobe, ул. Абая, 25",
      time: "20:00",
      price: 5000,
      description: "Насладитесь живой джазовой музыкой...",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVyclu4PJWchxIljUbWKbMuWzwCpsBzwpW5g&s"
    },
    {
      id: 6,
      name: "Мастер-класс «Фотография для начинающих»",
      category: "Образование и мастер-классы",
      date: "18 Декабря",
      location: "Творческое пространство Lens Studio, ул. Смагулова, 11",
      time: "15:00",
      price: 2500,
      description: "Изучите основы фотографии...",
      url: "https://fotoshkola.org/img/phpthumbof/RUS09065-2-1200.4b3e8d693191e22f09405d4345c455ba77.jpg"
    },
    {
      id: 7,
      name: "Кулинарный мастер-класс: Паста по-итальянски",
      category: "Еда и напитки",
      date: "16 Декабря",
      location: "Кулинарная школа Cook&Learn, ул. Баймагамбетова, 8",
      time: "18:00",
      price: 900,
      description: "Приготовьте идеальную пасту...",
      url: "https://xn--80aawjfrd1dav.xn--p1ai/wp-content/uploads/2021/10/%D0%A1%D0%BF%D0%B0%D0%B3%D0%B5%D1%82%D1%82%D0%B8-%D1%81%D0%B2%D0%BE%D0%B8%D0%BC%D0%B8-%D1%80%D1%83%D0%BA%D0%B0%D0%BC%D0%B8-300x300.jpg"
    },
    {
      id: 8,
      name: "Фестиваль кино: Современные казахские режиссеры",
      category: "Кино и театр",
      date: "10 Декабря",
      location: "Кинотеатр Arman, ул. Смагулова, 5",
      time: "12:00",
      price: 2000,
      description: "Показы фильмов и обсуждения...",
      url: "https://novoetv.kz/wp-content/uploads/2017/06/%D0%9D%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D1%8C.-%D0%A4%D0%B5%D1%81%D1%82%D0%B8%D0%B2%D0%B0%D0%BB%D1%8C-%D0%BA%D0%B8%D0%BD%D0%BE.jpg"
    },
    {
      id: 9,
      name: "Новогодняя ярмарка",
      category: "Ярмарки и выставки",
      date: "25 Декабря",
      location: "Центральная площадь, ул. Абая, 1",
      time: "10:00",
      price: 0,
      description: "Подарки, угощения и развлечения...",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVu_OW9o9Ps45HYxFWOvi-SrR4lyDGsNu5AA&s",
    },
    {
      id: 10,
      name: "Квест: Тайны старого города",
      category: "Развлечения",
      date: "15 Декабря",
      location: "Квест-комната Old City, ул. Алиханова, 2",
      time: "17:00",
      price: 1500,
      description: "Погрузитесь в увлекательную игру...",
      url: "https://bobrkrai.datacenter.by/wp-content/uploads/2021/04/%D0%90%D1%84%D0%B8%D1%88%D0%B0-%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%B0.jpg"
    },
    {
      id: 11,
      name: "Выставка современного искусства",
      category: "Ярмарки и выставки",
      date: "14 Декабря",
      location: "Арт-центр Modern Art, ул. Смагулова, 12",
      time: "11:00",
      price: 3000,
      description: "Работы современных художников...",
      url: "https://www.astanagid.kz/thumbs/750_500_5_100/muzej_sovremennogo_iskusstva_goroda_astany_foto4.jpg"
    },
    {
      id: 12,
      name: "Спектакль «Казахский эпос»",
      category: "Кино и театр",
      date: "22 Декабря",
      location: "Театр Aktobe Drama, ул. Баймагамбетова, 7",
      time: "19:30",
      price: 5400,
      description: "Истории о героях казахской степи...",
      url: "https://www.belcanto.ru/media/images/publication/24111718.jpg"
    },
    {
      id: 13,
      name: "Новогодний утренник для детей",
      category: "Детские мероприятия",
      date: "24 Декабря",
      location: "Детский центр Happy Kids, ул. Смагулова, 15",
      time: "10:00",
      price: 4500,
      description: "Игры, подарки и праздничная программа...",
      url: 'https://sxodim.com/uploads/images/2022/12/07/optimized/dad8694a8f7b14c4f6854885bf53c619_800xauto-q-85.jpg'
    },
    {
      id: 14,
      name: "Йога-ретрит: Внутренний покой",
      category: "Спорт и здоровье",
      date: "21 Декабря",
      location: "Зал Harmony Yoga, ул. Алиханова, 4",
      time: "9:00",
      price: 10200,
      description: "Целый день для души и тела...",
      url: 'https://www.oum.ru/upload/iblock/54b/1vbtt17axlttwazb29i46ios3jau3ufq.jpeg'
    },
    {
      id: 15,
      name: "Шоу иллюзиониста Максима Ортана",
      category: "Развлечения",
      date: "19 Декабря",
      location: "Концертный зал Magic Hall, ул. Абая, 18",
      time: "19:00",
      price: 1500,
      description: "Фокусы и магия в живом исполнении...",
      url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSz8vqVrydoDl-CPvJjsO4Fz-WZQscGsTHVBA&s'
    },
    {
      id: 16,
      name: "Вечер танцев: Латино и сальса",
      category: "Танцы и вечеринки",
      date: "17 Декабря",
      location: "Танцевальный клуб Salsa Aktobe, ул. Баймагамбетова, 10",
      time: "20:00",
      price: 2000,
      description: "Погрузитесь в мир латиноамериканских танцев...",
      url: 'https://sxodim.com/uploads/posts/2022/11/25/optimized/8d291474d83f63c6dea4bb139efbadc4_1400x790-q-85.jpg'
    },
    {
      id: 17,
      name: "Презентация книги «История степи»",
      category: "Литература и чтение",
      date: "13 Декабря",
      location: "Библиотека им. Ауэзова, ул. Абая, 22",
      time: "16:00",
      price: 0,
      description: "Встреча с автором и автограф-сессия...",
      url: 'https://sxodim.com/uploads/images/2024/04/23/optimized/026ef629ac7bd8e7f1a5aec579b0ae07_800xauto-q-85.jpg'
    },
    {
      id: 18,
      name: "Научное шоу для детей",
      category: "Детские мероприятия",
      date: "20 Декабря",
      location: "Научный центр Junior Lab, ул. Алиханова, 9",
      time: "11:00",
      price: 300,
      description: "Увлекательные эксперименты для малышей...",
      url: 'https://lh3.googleusercontent.com/proxy/ijtanIPjcZpwUp04QKM46uITZw6jJqXmWBmNzX5Xb9OrAEGyNnc8bEtvsTNd7yBBtbeS8afCp973sSaV9wjQ-8lP'
    },
    {
      id: 19,
      name: "Тренинг по лидерству",
      category: "Образование и мастер-классы",
      date: "9 Декабря",
      location: "Бизнес-центр Aktobe Office, ул. Абая, 3",
      time: "10:00",
      price: 1500,
      description: "Развивайте лидерские навыки...",
      url: 'https://lh4.googleusercontent.com/proxy/Ih-1i4GmtGaR4FChWMv3ig6id-d3BCpaRfFtycVwdWZwVc8h9CLyeXAlnyvAjL93ccuZk-gHdONUiFiPFsqP6LEBe4W3s4OxLIQqj3978BnhQ1QTN4bWCeQf2w'
    },
    {
      id: 20,
      name: "Ночь кино в Mount Orta",
      category: "Кино и театр",
      date: "29 Декабря",
      location: "Творческое пространство Mount Orta, ул. Смагулова, 9/1",
      time: "22:00",
      price: 5000,
      description: "Просмотр фильмов и обсуждения до утра...",
      url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8fmKV-ox0kB97Gs282z4V84A50U7JWe9y4Q&s'
    },
  ];
  